version: '1'
services:
  co-edit:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"
    volumes:
      - /app/node_modules
      - .:/app  
    env_file:
      - .env