# Stage 1: Build
FROM node:18 AS build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./

RUN npm install

# Copy the TypeScript source code
COPY tsconfig.json ./
COPY src ./src

# Compile TypeScript
RUN npm install -g typescript
RUN npx tsc || (echo "TypeScript compilation failed!" && exit 1)

COPY . .

# Start the app
CMD ["node", "dist/server.js"]
# CMD ["npm", "run", "start:dev"]
