name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master  # Change this if deploying from a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build and Push Docker Image to ECR
        run: |
          REPO_NAME="co-edit-server" # Change this to your ECR repo name
          IMAGE_TAG=$(echo $GITHUB_SHA | head -c 7)
          aws ecr create-repository --repository-name $REPO_NAME || true
          docker build -t $REPO_NAME:$IMAGE_TAG -f Dockerfile.dev .
          docker tag $REPO_NAME:$IMAGE_TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$REPO_NAME:$IMAGE_TAG
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$REPO_NAME:$IMAGE_TAG

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init my-app --platform docker --region $AWS_REGION
          eb deploy
